name: Java CI with Maven

on:
  push:
    branches: [ 'main' ]

jobs:
  test:
    name: Unit test
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      java-version: '17'
      maven-goal: 'clean verify'

  build:
    name: Build
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      java-version: '17'
      maven-goal: 'clean package -DskipTests'
