name: Reusable PostgreSQL Setup

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      maven-goal:
        required: true
        type: string
    secrets: inherit

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_DB: book_application
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Password

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Run Maven
        run: mvn -B ${{ inputs.maven-goal }} --file pom.xml
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/book_application
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: Password
